# Adicionando Colunas, Modificando Colunas e Valores

### Vamos pegar o nosso dataframe novamente

In [53]:
#importando biblioteca pandas
import pandas as pd
#importando biblioteca para ler characteres diferentes 
import chardet

#importando biblioteca para criação de gráficos e visualizações de dados
import matplotlib.pyplot as plt

In [54]:
with open("Contoso - Vendas  - 2017.csv", "rb") as f:
    result = chardet.detect(f.read(100000))  # Analisa parte do arquivo
    encoding_detected = result['encoding']

print(f"Codificação detectada: {encoding_detected}")

# Agora, tentar abrir o arquivo com a codificação correta

Codificação detectada: ascii

- Preparando as bases de dados

In [55]:

#às vezes precisaremos mudar o encoding. Possiveis valores para testar:
#encoding='latin1', encoding='ISO-8859-1', encoding='utf-8', encoding='cp1252'
#lendo cada arquivo csv da pasta
vendas_df = pd.read_csv('Contoso - Vendas  - 2017.csv', sep=';')
produtos_df = pd.read_csv("Contoso - Cadastro Produtos.csv",sep=';', encoding=encoding_detected)
lojas_df = pd.read_csv('Contoso - Lojas.csv',sep=';', encoding=encoding_detected)
novo_produtos_af = pd.read_csv("Contoso - Cadastro Produtos.csv",sep=';', encoding=encoding_detected)
clientes_df = pd.read_csv('Contoso - Clientes.csv',sep=';', encoding=encoding_detected)

#usaremos o display para ver todos os dataframes
#display(vendas_df)

UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 0: ordinal not in range(128)

In [ ]:
#usaremos o display para ver todos os dataframes
display(vendas_df)
display(produtos_df)
display(lojas_df)
display(clientes_df)

-Vamos tirar as colunas inúteis do clientes_df ou pegar apenas as colunas que quisermos

In [ ]:
#apagando colunas inuteis no df de cliente com .drop(), passando o eixo 1 que corresponde as colunas 
clientes_df = clientes_df.drop(['Unnamed: 7','Unnamed: 8','Unnamed: 9','Unnamed: 10'], axis=1)
clientes_df

In [ ]:
#selecionando colunas 
clientes_df = clientes_df[['ID Cliente','E-mail' ]]

#selecionando colunas no df de produtos
produtos_df = produtos_df[['ID Produto', 'Nome da Marca']]

#selecionando colunas no df lojas
lojas_df  = lojas_df[['ID Loja', 'Nome da Loja']]

#printando um df com display
display(produtos_df)

In [ ]:

#renomeandocoluna ÿID Loja lojas_df
lojas_df = lojas_df.rename(columns={'ÿID Loja': 'ID Loja'})
lojas_df

In [ ]:
#renomeando coluna ÿID Cliente no clientes_df
clientes_df = clientes_df.rename(columns={'ÿID Cliente' : 'ID Cliente',
                                          'E-mail': 'E-mail do Cliente'})
clientes_df

In [ ]:
#juntando os dataframes- passando o novo dataframe que recebe o antigo.merge(df que quer juntar, on='coluna que quer juntar')
#on='coluna que quer juntar' = nome da coluna que faz referencia as duas tabelas
vendas_df = vendas_df.merge(produtos_df, on='ID Produto')
vendas_df = vendas_df.merge(lojas_df, on='ID Loja')
#merge e mudando o nome da coluna 
vendas_df = vendas_df.merge(clientes_df, on='ID Cliente').rename(columns={'E-mail do Cliente_y': 'E-mail do Cliente'})

#printando o novo df de vendas que contem novas colunas
display(vendas_df)

In [61]:
vendas_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 980642 entries, 0 to 980641
Data columns (total 13 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Numero da Venda       980642 non-null  int64
 1   Data da Venda         980642 non-null  object
 2   Data do Envio         980642 non-null  object
 3   ID Canal              980642 non-null  int64
 4   ID Loja               980642 non-null  int64
 5   ID Produto            980642 non-null  int64
 6   ID Promocao           980642 non-null  int64
 7   ID Cliente            980642 non-null  int64
 8   Quantidade Vendida    980642 non-null  int64
 9   Quantidade Devolvida  980642 non-null  int64
 10  Nome da Marca         980642 non-null  object
 11  Nome da Loja          980642 non-null  object
 12  E-mail do Cliente     980642 non-null  object
dtypes: int64(8), object(5)
memory usage: 97.3+ MB

### Agora, e se quisermos acrescentar uma coluna com o mês, o dia e o ano de cada venda (e não só a data completa)

In [ ]:
#transformando o texto da coluna Data em datetime com a função to_datetime

vendas_df['Data da Venda'] = pd.to_datetime(vendas_df['Data da Venda'], format='%d/%m/%Y')
display(vendas_df)
vendas_df.info()

In [64]:
#Criando coluna Ano da Venda

vendas_df['Data da Venda'] = pd.to_datetime(vendas_df['Data da Venda'], format='%d/%m/%Y')
vendas_df['Ano da Venda'] = vendas_df['Data da Venda'].dt.year

#Criando coluna mes da Venda
vendas_df['Mes da Venda'] = vendas_df['Data da Venda'].dt.month
#Criando coluna dia da Venda
vendas_df['Dia da Venda'] = vendas_df['Data da Venda'].dt.day
display(vendas_df)
vendas_df.info()

,Numero da Venda,Data da Venda,Data do Envio,ID Canal,ID Loja,ID Produto,ID Promocao,ID Cliente,Quantidade Vendida,Quantidade Devolvida,Nome da Marca,Nome da Loja,E-mail do Cliente,Ano da Venda,Mes da Venda,Dia da Venda
0,1,2017-01-01,02/01/2017,1,86,981,2,6825,9,1,A. Datum,Loja Contoso Austin,rbrumfieldmy@ameblo.jp,2017,1,1
1,2,2017-01-01,06/01/2017,5,308,1586,2,18469,9,1,Southridge Video,Loja Contoso North America Reseller,cshawd4@technorati.com,2017,1,1
2,3,2017-01-01,01/01/2017,0,294,1444,5,19730,13,1,The Phone Company,Loja Contoso Tehran No.2,kgorriekd@bandcamp.com,2017,1,1
3,4,2017-01-01,01/01/2017,0,251,1468,5,29326,6,1,Contoso,Loja Contoso Singapore,angela49@adventure-works.com,2017,1,1
4,5,2017-01-01,07/01/2017,6,94,1106,2,22617,4,1,Contoso,Loja Contoso Grand Prairie,jacob4@adventure-works.com,2017,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
980637,980638,2017-12-31,31/12/2017,0,194,2490,4,10353,120,0,Contoso,Loja Contoso Ridgely,ocrosson9u@illinois.edu,2017,12,31
980638,980639,2017-12-31,06/01/2018,6,32,2488,4,31750,120,0,Contoso,Loja Contoso Milliken,victor11@adventure-works.com,2017,12,31
980639,980640,2017-12-31,03/01/2018,3,210,2511,10,12003,80,0,Contoso,Loja Contoso Cheshire,mtopaz4@gmpg.org,2017,12,31
980640,980641,2017-12-31,31/12/2017,0,53,436,4,25550,39,0,Adventure Works,Loja Contoso East Troy,lance5@adventure-works.com,2017,12,31
980641,980642,2017-12-31,31/12/2017,0,309,2510,10,28707,80,0,Contoso,Loja Contoso Europe Reseller,jan8@adventure-works.com,2017,12,31

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 980642 entries, 0 to 980641
Data columns (total 16 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Numero da Venda       980642 non-null  int64
 1   Data da Venda         980642 non-null  datetime64[ns]
 2   Data do Envio         980642 non-null  object
 3   ID Canal              980642 non-null  int64
 4   ID Loja               980642 non-null  int64
 5   ID Produto            980642 non-null  int64
 6   ID Promocao           980642 non-null  int64
 7   ID Cliente            980642 non-null  int64
 8   Quantidade Vendida    980642 non-null  int64
 9   Quantidade Devolvida  980642 non-null  int64
 10  Nome da Marca         980642 non-null  object
 11  Nome da Loja          980642 non-null  object
 12  E-mail do Cliente     980642 non-null  object
 13  Ano da Venda          980642 non-null  int32
 14  Mes da Venda          980642 non-null  int32
 15  Dia da Venda          980642 non-null  int32
dtypes: datetime64[ns](1), int32(3), int64(8), object(4)
memory usage: 108.5+ MB

### Antes de entrar no próximo exemplo, precisamos falar de 2 métodos:
    1. loc - permite pegar uma linha de acordo com o índice dela. Ele dá erro caso não encontre o índice. Isso é interessante principalmente quando o índice é uma informação relevante ao invés só do número do índice ou quando queremos pegar alguma linha específica do dataframe (ao invés de ir do início do dataframe até a linha 5, por exemplo).
        Também podemos usar como loc[índice_linha, índice_coluna] para acessar um valor específico e modificá-lo.
    2. iloc - enxerga o dataframe como linhas e colunas e consegue pegar o valor com um número de linha e um número de coluna. Repara que ele não analisa o valor do índice da linha e da coluna, apenas a posição importa.
        Uso: iloc[num_linha, num_coluna]
        
- Vendo na prática

In [ ]:
#vamos pegar o preço produto Contoso Optical Wheel OEM PS/2 Mouse E60 Black
#por loc

#por iloc

### A empresa decidiu aumentar o preço do produto ID 873 (Contoso Wireless Laser Mouse E50 Grey) para 23 reais. Como fazemos, para modificar isso na nossa base?

In [ ]:
#novo_produtos_df.loc['Contoso Wireless Laser Mouse E50 Grey', 'Preco Unitario'] = 23